### ISSUE TITLE
Range requests

### ISSUE THREAD

**Issue by calpaterson** [calpaterson/csvbase#29]
# Brief overview

AS A user of csvs via some external services, like csvplot

I WANT HTTP range request features

SO THAT ???

# Additional details

Needs investigation. Would be nice to support this to allow people to resume downloads, download in chunks and similar

https://news.ycombinator.com/item?id=34417858

**Comment by tboerstad** [comment]
Thanks for creating an issue. 

Here is a suggested solution:
Add `Content-Range` to the Access-Control-Allow-Headers on the server which is hosting csvbase.com

Here is more context to the problem:
1. [PapaParse](https://www.papaparse.com) is a popular CSV parser for javascript.
2. PapaParse has been designed to support large datasets, which might not fit in browser memory. (I'm not sure if there are any such datasets (multiple GBs) on csvbase)
3. PapaParse has support for streaming remote files from an URL. If it's a cross origin requests, then the remote server must support it through CORS. csvbase.com already supports CORS. [Here is an example where csvplot.com](https://csvplot.com/remote_file.html?url=https://csvbase.com/ubieratlupa/monuments) is used to plot a dataset hosted on csvbase.com 

This is the core of this GitHub issue:
4. To enable streaming of large files, PapaParse uses the [HTTP Range](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range) header to specify how many bytes of the dataset it wants per request. I think, not sure, the response header will then contain a [Content-Range](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Range) header, which PapaParse tries read. On csvbase.com, the Content-Range header is not allowed to be read due to CORS-restrictions. 

To check if the problem exists, you can load a [remote URL on the PapaParse demo page](https://www.papaparse.com/demo), with the `Stream` checkbox enables.  In the dev console, you should see a message `Refused to get unsafe header "Content-Range"` if the remote server does not allow `Content-Range`. 
Note that this message does not appear in Safari 16.2, but it does appear in Chrome 108.

**Comment by calpaterson** [comment]
csvbase doesn't currently implement range requests so while the CORS error is misleading it's not really wrong.

I think it is going to be quite hard to implement range requests because csvbase is generating these csv files dynamically - we actually store the data in SQL and return different formats when people ask.

Reading up on range requests, they are typically oriented around bytes (this doesn't have to be the case and we could better support lines - though PapaParse, along with many other clients, don't support custom range units).  

csvbase does not know where, eg, byte N is going to be before we generate at least the first N bytes of a file.  It's possible that someone might request, say, the last 1mb of a 1gb table and we would have to read and discard the first 999mb of a generated csv in order to do that.  So while a client could use ranges to avoid having to load the whole of a large file it would mean that csvbase would have to repeatedly load a large file into memory for you (or implement some custom in-application cache).

I think a better approach for clients reading large files is to process them line by line.  Python, for example, does this when you do:

```python
import csv, requests

r = requests.get("https://csvbase.com/meripaterson/stock-exchanges", stream=True)
reader = csv.reader(line.decode("utf-8") for line in r.iter_lines())

for row in reader:
    print(row)
```

This allows you to avoid reading the whole file into memory regardless of whether or not range requests are supported.  

This also has the benefit of working better with HTTP caching which is something csvbase is probably going to make more use of eventually (and which range requests don't really work well with).

I hope that helps, I'm sorry that's the answer

**Comment by calpaterson** [comment]
Hi again.  After thinking a bit harder, I have found a way to do this anyway.  Next release will support the Range header!

**Comment by calpaterson** [comment]
This was enabled a while ago and I just got around to checking and - range requests now work on production.  Thanks for making a case for it.

**Comment by tboerstad** [comment]
Awesome, can confirm it works from my side to 🙌
