### ISSUE TITLE
Unusable on slower connection

### ISSUE THREAD

**Issue by Jak2k** [calpaterson/csvbase#64]
# Brief overview

AS A user, who has a slower internet connection

I WANT a client side navigation

SO THAT the page doesn't have to fully reload and the feedback after a click comes faster

# Additional details
Have a look at [HTMX](https://htmx.org/)

**Comment by calpaterson** [comment]
Hi - thanks for raising this.  I do test on bandwidth constrained/high latency connections (to some extent, I have one).

When I emulate a 2G/"Slow 3G" connection using Firefox/Chrome I can't any pages which take more than a few seconds to load.  

My feeling is the max acceptable load time for an HTML page on a ok connection would be about 2 seconds.  For a poor quality connection, perhaps I'd multiply that by 2 or 3.  I'm not counting a first page load with a empty HTTP cache because using client-side navigation wouldn't improve that.

Can you share your numbers?  What pages are you having problems with?  And if I used HTMX, would that reduce the number of network roundtrips somehow?

**Comment by Jak2k** [comment]
HTMX would reduce the data loaded, because on an action, only parts of the site are refetched. Caching currently doesn't help as the HTML is dynamic generated and has to be refetched.

**Comment by calpaterson** [comment]
I don't think it would reduce the number of network roundtrips though, which is usually the main problem on mobile phones (ie: latency).

Can you help by providing numbers for a page load (or transition) which you think is unusably slow on the site as it is now?
